import "/public/css/bootstrap.min.css"
import "/public/fonts/font-icons.css"
import "/public/fonts/fonts.css"
// import "/public/css/nouislider.min.css"
import "/public/css/swiper-bundle.min.css"
import "/public/css/animate.css"
import "/public/css/styles.css"

import { DM_Sans, Josefin_Sans } from 'next/font/google'
import Script from 'next/script'
import { DirectionProvider, directionBootstrapScript } from '@/context/DirectionContext'
import DirectionToggle from '@/components/elements/DirectionToggle'

const dm = DM_Sans({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	variable: "--dm",
	display: 'swap',
})
const josefin = Josefin_Sans({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	variable: "--josefin",
	display: 'swap',
})


export const metadata = {
	title: 'Homzen - Real Estate Next.js Template',
	description: 'Generated by create next app',
	icons: {
		icon: ['/images/logo/favicon.png']
	}
}

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${dm.variable} ${josefin.variable} body`} suppressHydrationWarning>
				<Script id="direction-bootstrap" strategy="beforeInteractive" dangerouslySetInnerHTML={{ __html: directionBootstrapScript }} />
				<DirectionProvider>
					{children}
					<DirectionToggle />
				</DirectionProvider>
			</body>
		</html>
	)
}
